USE EMARKET;


-- Equipe: Matheus Ribeiro Reis, Marcus Túlio, Diego Reis, Diogo Rodrigues
-- CATEGORIAS E PROTUDOS

SELECT * FROM CATEGORIAS; -- 01
SELECT CATEGORIANOME, DESCRICAO FROM CATEGORIAS; -- 02
SELECT * FROM PRODUTOS; -- 03
SELECT PRODUTONOME, PROVEDORID FROM PRODUTOS WHERE PROVEDORID = 8; -- 4
SELECT * FROM PRODUTOS WHERE PRECOUNITARIO BETWEEN 10 AND 22; -- 5
SELECT * FROM PRODUTOS WHERE UNIDADESPEDIDAS = 0 ORDER BY UNIDADESPEDIDAS ASC; -- 6

-- CLIENTES 

SELECT CONTATO, EMPRESA, TITULO, PAIS FROM CLIENTES ORDER BY PAIS ASC; -- 1
SELECT * FROM CLIENTES WHERE TITULO = "OWNER" ORDER BY TITULO ASC; -- 2
SELECT CONTATO FROM CLIENTES WHERE CONTATO LIKE CONTATO = "C%"; -- 3

-- FATURA

SELECT * FROM FATURAS;
SELECT DATAFATURA FROM FATURAS WHERE DATAFATURA ORDER BY DATAFATURA ASC; -- 1
SELECT PAISENVIO, FORMAENVIO FROM FATURAS WHERE FORMAENVIO != 3; -- 2
SELECT * FROM FATURAS WHERE EMPREGADOID = 2 AND EMPREGADOID = 3 AND EMPREGADOID = 5 AND EMPREGADOID = 8 AND EMPREGADOID = 9; -- 3 

-- PRODUTOS PRT2

SELECT * FROM PRODUTOS;
SELECT * FROM PRODUTOS WHERE PRECOUNITARIO ORDER BY PRECOUNITARIO DESC; -- 1
SELECT * FROM PRODUTOS WHERE PRECOUNITARIO ORDER BY PRECOUNITARIO DESC LIMIT 5 OFFSET 0 ; -- 2
SELECT * FROM PRODUTOS WHERE UNIDADESESTOQUE ORDER BY UNIDADESESTOQUE DESC LIMIT 10 OFFSET 0; -- 3

-- DETALHEFATURA 

SELECT * FROM DETALHEFATURA;
SELECT FATURAID, PRODUTOID, QUANTIDADE FROM DETALHEFATURA; -- 1
SELECT FATURAID, PRODUTOID, QUANTIDADE FROM DETALHEFATURA ORDER BY QUANTIDADE DESC; -- 2
SELECT FATURAID, PRODUTOID, QUANTIDADE FROM DETALHEFATURA WHERE QUANTIDADE BETWEEN 50 AND 100; -- 3
SELECT FATURAID, PRODUTOID, PRECOUNITARIO * QUANTIDADE FROM DETALHEFATURA; -- 4