-- FUNÇÕES DE AGREGAÇÃO
-- OBJETIVOS: MONTAR CONSULTAS(SELECTS) QUE VISAM RETORNAR OS DADOS DE MANEIRA AGRUPADA/RESUMIDA A PARTIR
-- DE UM CONJUNTO DE DADOS

USE EMarket;

-- FUNÇÃO COUNT
-- OBJETIVO: CONTAR A QUANTIDADE DE REGISTROS QUE FORAM ENCONTRADOS A PARTIR DO SELECT INFORMADO
-- COUNT PARA TRAZER A QUANTIDADE DE REGISTROS DA TABELA DE FATURAS
SELECT
	COUNT(*)
FROM Faturas;

-- COUNT PARA TRAZER A QUANTIDADE DE FATURAS DA CIDADE DO RIO DE JANEIRO
SELECT
	COUNT(*) AS 'QUANTIDADE DE FATURAS DO RIO DE JANEIRO'
FROM Faturas
WHERE
	CidadeEnvio = 'Rio de Janeiro';

-- MAX
-- OBJETIVO: RETORNAR O VALOR MÁXIMO A PARTIR DE UM CONJUNTO DE DADOS
SELECT
	MAX(Transporte)
FROM Faturas;

-- MIN
-- OBJETIVO: RETORNAR O VALOR MÍNIMO A PARTIR DE UM CONJUNTO DE DADOS
SELECT
	MIN(Transporte)
FROM Faturas;

-- AVG
-- OBJETIVO: RETORNAR A MÉDIA A PARTIR DE UM CONJUNTO DE DADOS
SELECT
	AVG(Transporte)
FROM Faturas;

-- FUNÇÃO DE FORMATAÇÃO
SELECT
	ROUND(AVG(Transporte), 2)
FROM Faturas;

-- SUM
-- OBJETIVO: SOMAR OS DADOS A PARTIR DE UM CONJUNTO DE DADOS
SELECT
	ROUND(SUM(Transporte), 2)
FROM Faturas;

-- GROUP BY
-- OBJETIVO: RETORNAR UM CONJUNTO DE DADOS QUE SE REPETE
SELECT
	CidadeEnvio,
    COUNT(*) as 'QUANTIDADE DE VEZES QUE A CIDADE SE REPETE'
FROM Faturas
GROUP BY
	CidadeEnvio
ORDER BY
	CidadeEnvio;
    
SELECT
	CidadeEnvio
FROM Faturas
ORDER BY
	CidadeEnvio;

-- HAVING
-- OBJETIVO: APLICAR UMA CONDIÇÃO AO GROUP BY
SELECT
	CidadeEnvio,
    COUNT(*) AS QTD
FROM Faturas
GROUP BY
	CidadeEnvio
HAVING
	QTD > 30
ORDER BY
	CidadeEnvio;

-- FUNÇÕES DE FORMATAÇÃO
-- OBJETIVO: FORMATAR OS DADOS RETORNADOS A PARTIR DE UM SELECT
-- CAST()
-- CONCAT()
-- DATE_FORMAT()
SELECT
	*
FROM Faturas;

SELECT
	DATE_FORMAT(DataRegistro, '%d/%m/%y')
FROM Faturas;

SELECT
	CONCAT(FaturaID, ClienteID)
FROM Faturas;

-- SUBQUERIES
-- OBJETIVO: REALIZAR BUSCAS DE DADOS DE FORMA DINÂMICA
-- PREMISSA UMA LINHA E UMA COLUNA
SELECT
	*
FROM Faturas;

SELECT
	*
FROM Clientes;

SELECT
	*
FROM Faturas
WHERE
	ClienteID = 'ALFKI';

SELECT
	*
FROM Faturas
WHERE
	ClienteID = (
		SELECT 
			ClienteID 
		FROM Clientes 
        WHERE Contato = 'Maria Anders' 
        AND Titulo = 'Sales Representative' 
        AND Endereco = 'Obere Str. 57'
	);