CREATE DATABASE DHTUBE;
USE DHTUBE;

CREATE TABLE AVATAR (
 ID_AVATAR INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
 NOME VARCHAR (45),
 URL_IMAGEM VARCHAR (100)
);

CREATE TABLE PAIS (
	ID_PAIS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (100)
);

CREATE TABLE USUARIO (
	ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (45),
    EMAIL VARCHAR (45),
    SENHA VARCHAR (45),
    DATA_NASCIMENTO DATETIME,
    CEP VARCHAR (45),
    ID_PAIS INT  NOT NULL,
    ID_AVATAR INT NOT NULL,
    CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS),
    CONSTRAINT FK_USUARIO_AVATAR FOREIGN KEY (ID_AVATAR) REFERENCES AVATAR (ID_AVATAR)
);

CREATE TABLE PLAYLIST (
	ID_PLAYLIST INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (45),
    DATA_CRIACAO DATETIME, 
    PRIVADO SMALLINT (6),
    ID_USUARIO INT (11),
    CONSTRAINT FK_PLAYLIST_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

-- INSERT 

INSERT INTO PLAYLIST (NOME, DATA_CRIACAO)
VALUES 
("FORRO SO AS MELHORES", "2002-10-05"),
("É SÓ ROCK", "2010-09-12"),
("É SÓ PAGODE", "2015-07-07"),
("DEUS EH FIEL", "2020-06-06");

-- UPDATE

UPDATE PLAYLIST 
SET NOME = "É SÓ FUNK"
WHERE ID_PLAYLIST = 4;

-- DELETE 

DELETE FROM PLAYLIST WHERE ID_PLAYLIST = 4

-- SELECT 

SELECT * FROM PLAYLIST 


-- EQUIPE: MATHEUS RIBEIRO, FELIPE TELES, VALQUIRIA SILVA





 
