															--  DDL --
            CREATE DATABASE GUILDA_DOS_AVENTUREIROS;
			USE GUILDA_DOS_AVENTUREIROS;

			CREATE TABLE `GUILDA_DOS_AVENTUREIROS`.`TB_REQUISITADOR`(
			ID_REQUISITADOR INT NOT NULL AUTO_INCREMENT,
			NOME VARCHAR (150),
			SOBRENOME VARCHAR (155),
			PRIMARY KEY (ID_REQUISITADOR));

			CREATE TABLE `GUILDA_DOS_AVENTUREIROS`.`TB_AVENTUREIRO`(
			ID_AVENTUREIRO INT NOT NULL AUTO_INCREMENT,
			NOME VARCHAR (150),
			SOBRENOME VARCHAR (150),
			CLASSE VARCHAR (150) NOT NULL,
			PRIMARY KEY (ID_AVENTUREIRO));

			CREATE TABLE `GUILDA_DOS_AVENTUREIROS`.`TB_ALQUIMISTA`(
			ID_ALQUIMISTA INT NOT NULL AUTO_INCREMENT,
			NOME_DAS_POCOES VARCHAR (255),
			EXPORTACOES DATETIME,
			PRIMARY KEY (ID_ALQUIMISTA));

			CREATE TABLE `GUILDA_DOS_AVENTUREIROS`.`TB_FERREIRO`(
			ID_FERREIRO INT NOT NULL AUTO_INCREMENT,
			NOME_ARMADURA VARCHAR (255),
			NOME_ARMA VARCHAR (255),
			EXPORTACOES DATETIME,
			PRIMARY KEY (ID_FERREIRO));


			CREATE TABLE `GUILDA_DOS_AVENTUREIROS`.`TB_ARMAZEM`(
			ID_ARMAZEM INT NOT NULL AUTO_INCREMENT,
			IMPORTACOES_ALQUIMISTA DATETIME NOT NULL,
			IMPORTACOES_FERREIRO DATETIME NOT NULL,
			ID_FERREIRO INT NOT NULL,
			ID_ALQUIMISTA INT NOT NULL,
			PRIMARY KEY (ID_ARMAZEM),
			CONSTRAINT `FK_FERREIRO`
			FOREIGN KEY (ID_FERREIRO)
			REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_FERREIRO`(ID_FERREIRO),
			CONSTRAINT `FK_ALQUIMISTA`
			FOREIGN KEY (ID_ALQUIMISTA)
			REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_ALQUIMISTA`(ID_ALQUIMISTA));

			CREATE TABLE `GUILDA_DOS_AVENTUREIROS`.`TB_LOJA_DA_GUILDA`(
			ID_LOJA_DA_GUILDA INT NOT NULL AUTO_INCREMENT,
			POCOES VARCHAR (255),
			ARMAS VARCHAR (255),
			ARMADURAS VARCHAR (255),
			PRECO_POCOES DECIMAL,
			PRECO_ARMAS DECIMAL,
			PRECO_ARMADURAS DECIMAL,
			ID_ARMAZEM INT NOT NULL,
			PRIMARY KEY (ID_LOJA_DA_GUILDA),
			CONSTRAINT `FK_ARMAZEM`
			FOREIGN KEY (ID_ARMAZEM)
			REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_ARMAZEM` (ID_ARMAZEM));

			CREATE TABLE `GUILDA_DOS_AVENTUREIROS`.`TB_BANCO_DA_GUILDA` (
			ID_BANCO INT NOT NULL AUTO_INCREMENT, 
			ID_REQUISITADOR INT NOT NULL,
			ID_LOJA_DA_GUILDA INT NOT NULL,
			PRIMARY KEY (ID_BANCO),
			CONSTRAINT `FK_REQUISITADOR`
			FOREIGN KEY (ID_REQUISITADOR)
			REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_REQUISITADOR`(ID_REQUISITADOR),
			CONSTRAINT `FK_LOJA_DA_GUILDA`
			FOREIGN KEY (ID_LOJA_DA_GUILDA)
			REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_LOJA_DA_GUILDA`(ID_LOJA_DA_GUILDA));

			CREATE TABLE `GUILDA_DOS_AVENTUREIROS`.`TB_MISSOES`(
			ID_MISSOES INT NOT NULL AUTO_INCREMENT,
			RECOMPENSA DECIMAL, 
			DATA_DE_REQUISICAO DATE,
			DATA_DE_CONCLUSAO DATETIME,
			DESCRICAO TEXT,
			ID_REQUISITADORES INT,
			ID_AVENTUREIROS INT NOT NULL,
			ID_BANCO INT NOT NULL,
			PRIMARY KEY (ID_MISSOES),
			CONSTRAINT `FK_AVENTUREIROS`
				FOREIGN KEY (`ID_AVENTUREIROS`)
				REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_AVENTUREIRO` (`ID_AVENTUREIRO`),
				  CONSTRAINT `FK_REQUISITADORES`
			FOREIGN KEY (`ID_REQUISITADORES`)
			REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_REQUISITADOR` (`ID_REQUISITADOR`),
			  CONSTRAINT `FK_BANCO_DA_GUILDA`
		FOREIGN KEY (`ID_BANCO`)
		REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_BANCO_DA_GUILDA` (`ID_BANCO`));
        
        CREATE TABLE `GUILDA_DOS_AVENTUREIROS`.`GUILDA_DE_AVENTUREIROS`(
        ID_GUILDA INT NOT NULL AUTO_INCREMENT,
        ID_MISSOES_ INT NOT NULL,
        ID_BANCO_DA_GUILDA_ INT NOT NULL,
        ID_LOJA_DA_GUILDA_ INT NOT NULL,
        PRIMARY KEY (ID_GUILDA),
        CONSTRAINT `FK_MISSOES_`
        FOREIGN KEY (`ID_MISSOES_`)
        REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_MISSOES`(ID_MISSOES),
        CONSTRAINT `FK_BANCO_DA_GUILDA_`
        FOREIGN KEY (`ID_BANCO_DA_GUILDA_`)
        REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_BANCO_DA_GUILDA` (ID_BANCO),
        CONSTRAINT `FK_LOJA_DA_GUILDA_`
        FOREIGN KEY (`ID_LOJA_DA_GUILDA_`)
        REFERENCES `GUILDA_DOS_AVENTUREIROS`.`TB_LOJA_DA_GUILDA` (ID_LOJA_DA_GUILDA));
        

															-- DML --
													-- SELECT + INSERT --
		SELECT * FROM TB_AVENTUREIRO;
        
        INSERT INTO TB_AVENTUREIRO (NOME, SOBRENOME, CLASSE)
			VALUES ('Azra Avani', 'Midmoon', 'Death Knight');
		INSERT INTO TB_AVENTUREIRO (NOME, SOBRENOME, CLASSE)
			VALUES ('Dronine', 'Midmoon', 'Summuner');
        INSERT INTO TB_AVENTUREIRO (NOME, SOBRENOME, CLASSE)
			VALUES ('Awaleff', 'Sunstar', 'Rogue');
		INSERT INTO TB_AVENTUREIRO (NOME,SOBRENOME,CLASSE)
			VALUES ('Jotaro','Joestar','Fighter');
            
														-- UPDATE --
            
		UPDATE TB_AVENTUREIRO 
        SET NOME = 'Lespring', SOBRENOME = 'Oscarchur', CLASSE = 'Paladin'
        WHERE ID_AVENTUREIRO = 2;
        
														-- DELETE --
        
        DELETE FROM TB_AVENTUREIRO WHERE ID_AVENTUREIRO = 4;
        
        
        